# Generated by Django 6.0.6 on 2026-06-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer_index', models.IntegerField()),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(default='متوسط', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('target_rank', models.CharField(max_length=100)),
                ('daily_study_hours', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('number_of_questions', models.IntegerField(default=12)),
                ('correct_answers', models.IntegerField(default=0)),
                ('readiness_percentage', models.FloatField(default=0.0)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.user')),
            ],
        ),
    ]
