# Generated by Django 6.0.6 on 2026-06-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auth_and_persistence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
