# Generated by Django 6.0.6 on 2026-06-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_quizquestion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='source_page',
        ),
    ]
